management:
  health:
    customhealthcheck:
      enabled: true


user-auth:
  openapi:
    dev-url: 'http://localhost:8080'
    prod-url: 'https://share-user-api.com'

---
spring:
  config:
    activate:
      on-profile: local

# Enable management endpoint details
management:
  endpoint:
    health:
      show-details: always

# Show debug logs
logging:
  level:
    com.share.userauthms: DEBUG
    org.springframework.security.web: DEBUG


# Customise swagger url
springdoc:
  swagger-ui:
    path: 'swagger-ui-home.html'