on:
  workflow_call:
    inputs:
      java-version:
        description: 'Select Java version'
        default: '17'
        required: true
        type: string

jobs:
  call-pr-build-workflow:
    uses: theshareplatform/share-reusable-workflows/.github/workflows/pr-build.yaml